### ISSUE TITLE
step 1: create a 0.0.1 release that simdjson-rs can depend on for ARM?

### ISSUE THREAD

**Issue by sunnygleason** [simd-lite/simd-lite#1]
Thinking maybe:

* extract from the stdarch pull request (https://github.com/rust-lang/stdarch/pull/792)
* just the subset necessary for ARM/Aarch64
* mostly generated, maybe a little manual coding
* super minimal

That would let us spark some interest in simdjson-rs ARM version,
and possibly gain ideas/advice from other simd folks?

**Comment by Licenser** [comment]
See: https://github.com/simd-lite/simdjson-rs/pull/39 huzza!

**Comment by sunnygleason** [comment]
nice! resolving, woot!
