### ISSUE TITLE
remove dependency on `table_lookup_tests.rs` (if possible)

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simd-lite#9]
from my read `table_lookup_tests.rs` is for lookup commands that are implemented in std::arch::arm so we probably don't need it unless i missed something (which is likely :P)

**Comment by sunnygleason** [comment]
right now, yes, deleteable... but it's there in hopes we adopt #11 ... 😄

**Comment by sunnygleason** [comment]
see #12 , yay!
